[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = []

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
known-first-party = ["task_tracker"]
